/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_thingsbook_it_LibGit2 */
#ifndef _Included_com_thingsbook_it_NativeGit
#define _Included_com_thingsbook_it_NativeGit
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_thingsbook_it_Git
 * Method:    doClone
 * Signature: (Ljava/lang/String;Ljava/lang/String)I
 */
JNIEXPORT jint JNICALL Java_com_thingsbook_it_NativeGit_doClone
(JNIEnv *, jclass, jstring, jstring);

JNIEXPORT jint JNICALL Java_com_thingsbook_it_NativeGit_JNI_Onload
(JavaVM* jvm, void *reserved);


#ifdef __cplusplus
}
#endif
#endif
